version: "3.7"

services:
  rabbit:
    image: rabbitmq:3.9.7-management-alpine
    container_name: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=oFbmhtLdJz5GCYt5
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=Eqqz6fXGyhXTpmN8
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/redis.conf
    command: [ "redis-server", "/redis.conf" ]

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elastic
    hostname: elastic
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elastic-data:/usr/share/elasticsearch/data

volumes:
  rabbitmq-data:
  mongodb-data:
  redis-data:
  elastic-data:
